### ISSUE TITLE
Legacy plugin not compatible 

### ISSUE THREAD

**Issue by jasondibenedetto** [nystudio107/craft-vite#20]
### Describe the bug
In vite 2.7, the name of the legacy-polyfills entry has changed from "vite/legacy-polyfills" to "\u0000vite/legacy-polyfills" which seems to be causing issues loading the legacy polyfill file.

This issue is discussed in both https://github.com/vitejs/vite/issues/6097 and https://github.com/ElMassimo/vite_ruby/issues/156

### Versions
- Plugin version: 1.0.15
- Craft version: 3.7.25.1

**Comment by khalwat** [comment]
This is very likely an issue with Vite `\u0000` is the Unicode character for `null`

I'm assuming this is some kind of a mistake either in Vite or in the Legacy plugin.

While I can "fix" this, I want to be sure that it's intentional on Vite's end to change the name of this polyfill. Prefacing it with the Unicode character for `null` feels to me like it potentially could be a mistake

**Comment by jasondibenedetto** [comment]
Yes I was unsure which end this bug needs to be resolved on. After seeing the issue on `vite_ruby`, I thought it was worth flagging.

**Comment by khalwat** [comment]
Yeah I commented on that issue -> https://github.com/ElMassimo/vite_ruby/issues/156#issuecomment-998401899

My spidey-sense is telling me that this is actually a bug, it's pretty unlikely they'd randomly decide to prefix virtual modules with the Unicode for `null` (`\u0000`).

**Comment by khalwat** [comment]
Fixed via this PR (which is not yet merged, but I'm assuming will be):

https://github.com/vitejs/vite/pull/6225

**Comment by khalwat** [comment]
Fixed in Vite 2.7.6, just released -> https://github.com/vitejs/vite/blob/v2.7.6/packages/vite/CHANGELOG.md
