### ISSUE TITLE
The reason why everything is outputted from 1 line of twig code

### ISSUE THREAD

**Issue by kevinmu17** [nystudio107/craft-vite#26]
### Question
I'm struggling with splitting the output. I want only the CSS to be rendered in the `<head>` tags and the scripts before `</body>`
Is there a way to do this?

### Additional context
I'm coming from TwigPack where this was possible :) I was very much intrigued by Vite.JS and it's performance so I'm investigating this plugin and setup with Nitro (no luck yet, but if the above is not possible I'm not sure this is my way to go)

Thanks!

**Comment by khalwat** [comment]
That's not how Vite works. Additionally, since the script tags are rendered as `<script type="module">` they are automatically deferred, so putting them in the `<head>` is the right way to do it. It will cause them to be fetched early, but not executed until the DOM is parsed.

See: https://gist.github.com/jakub-g/385ee6b41085303a53ad92c7c8afd7a6

I would recommend against using Nitro until it is capable of working with modern frontend development. I'd suggest looking at DDEV instead. https://ddev.readthedocs.io/en/stable/
