### ISSUE TITLE
Default ASYNC_CSS to false

### ISSUE THREAD

**Issue by phillanier** [nystudio107/craft-vite#82]
### Is your feature request related to a problem? Please describe.
I contemplated filing this as a bug, since it probably affects the vast majority of people using this otherwise outstanding plugin, but that seemed a little harsh. The basic issue is that when stylesheets are loaded asynchronously, even the simplest site will exhibit an unwanted flash of unstyled content, as the page will render before the stylesheet is even requested from the server. Pretty much the only exception would be if the site also implements critical CSS. But that's by far going to be the exception rather than the rule. 

### Describe the solution you would like
ASYNC_CSS should default to false. Yeah, there's a note about it at the end of the documentation, but it's easy to miss, most copy-paste code samples don't include this parameter, and many developers may not even recognize what it means. On the other hand, if a developer has implemented critical CSS, they surely will know what this all about. 

Of course, at this point the issue might be introducing breaking changes / backward compatibility. Perhaps we could only default to true if criticalPath (or other related properties) have been set??

### Describe alternatives you have considered
We're explicitly setting the ASYNC_CSS parameter. Using critical CSS would also be an alternative. But mainly looking out for the typical user/developer who don't understand why their site loads janky when they use this plugin.

### Additional context
1. Not gonna start an argument one way or another about whether critical CSS is a best practice or when to use. But I think it's safe to say that the vast majority of classic page-based sites (as opposed to SPAs) don't follow this pattern. 
2. I've seen two separate Craft projects where the developer's solution to the FOUSC was to hide all page content until the vite-script-loaded event fired. :-)

**Comment by khalwat** [comment]
This is done on purpose, because ideally, you want to be doing Critical CSS along with an async stylesheet.

https://nystudio107.com/blog/implementing-critical-css

You make a good point that someone who knows about Critical CSS would probably also know to look for a setting to ensure the stylesheet is async, but it's a pattern I always use, and like to encourage others to use as well.

So with that in mind, I'll see if I can figure out a way that it could be changed without breaking backwards compatibility.

I'm a little worried about the default changing based on another setting (critical path in this case) but I can't think of another alternative at the moment.

**Comment by khalwat** [comment]
I decided to just add a callout more prominently to the docs in the hopes that it would mitigate the issue.

<img width="724" alt="Screenshot 2024-02-28 at 10 31 01 PM" src="https://github.com/nystudio107/craft-vite/assets/7570798/52adadc5-3c3a-450f-83ed-ca14f62a54da">
