### ISSUE TITLE
ValueError: Path cannot be empty (FileHelper.php)

### ISSUE THREAD

**Issue by mprofitlich** [nystudio107/craft-vite#95]
I’ve taken the configuration from a project Craft Vite already runs on. In the project I copied the configuration to I get this error:
ValueError
Path cannot be empty
in /var/www/html/vendor/nystudio107/craft-plugin-vite/src/helpers/FileHelper.php at line 91 – file_get_contents('')

I’ve set up two sites in Craft. Could this be related to sites? What can I do to encircle the error? What is `file_get_contents('')` for? Thanks for pointing me into the right direction.

The error messages: https://pastebin.com/g4akWakG

**Comment by khalwat** [comment]
It's hard to say from here because I don't have anything to go on really (your configuration, etc) but I'd say look for differences between the implementation on the site where it works, and the new site where it does not.

Probably one of the settings in `config/vite.php` isn't correct for the new project.

**Comment by mprofitlich** [comment]
Thanks for your look at my issue. As advised I double checked the configuration. Then I realised that the error occured even after deinstalling craft-vite. The error did not come from craft-vite but from craft-plugin-vite that got installed as a dependency of craftpulse/craft-password-policy. I deinstalled craft-password-policy, then the site worked again. Then I installed craftpulse/craft-password-policy again and the site still works.

The solution thus is to do a `composer remove`.
